### ISSUE TITLE
input as 8bit jpg?

### ISSUE THREAD

**Issue by ArsenLuca** [yuanming-hu/exposure#10]
Have you tried 8bit jpg as input? If so, How about the performance？

**Comment by yuanming-hu** [comment]
I did. We have some internal projects (which I cannot disclose now, sorry) that actually have only 8-bit inputs. The results are actually as good as 16-bit inputs. However, from time to time you may find posterization/saturation artifacts due to the lack of color depth (intensity resolution/resolution).

**Comment by yuanming-hu** [comment]
Thanks for the question. I have added it to FAQ(2).
