### ISSUE TITLE
if remove the rl part, just use a fixed pipeline, will the result be similiar

### ISSUE THREAD

**Issue by vissac** [yuanming-hu/exposure#18]
Hi, I'm wondering if remove the rl part and just use a fixed pipeline with wgan, will the fixed pipeline generate a similar result.

**Comment by yuanming-hu** [comment]
You are welcome to have a try, but here are some possible issues with this approach:
 - To be as expressive as the original approach, in the fixed pipeline can be significantly longer because the selection of filters is disabled.
 - It may be difficult to actually figure out the order of the operations in the fixed pipeline.

These two drawbacks may harm human understandability, which is one of the most important features of our system. On the other hand, the benefit of removing RL is more stability.

Keep me posted if you have any results!

**Comment by yuanming-hu** [comment]
So my conclusion my guess is that the image quality should be similar, the system will be simpler, but the operation sequence may be worse.

**Comment by Oktai15** [comment]
@yuanming-hu, hi! You said about fixed pipeline and order of the operations. Imagine that we have only 3 filters and, as far as I understood your idea correctly,  we need to set order. What do you think it is important to set this order in special way or it can be in any order? This is a debatable question, because applying filters often are not commutative. 

What do you mean this: "the fixed pipeline can be significantly longer than the version with RL because the selection of filters is disabled"? Why is it longer than RL? I suppose we need to apply only 3 filters (my example) in certain order with before selected parameters.

**Comment by xiaozhi2015** [comment]
Mark.
