### ISSUE TITLE
Evaluate an image with 3500ms-4000ms. Not 30ms?

### ISSUE THREAD

**Issue by vikiQiu** [yuanming-hu/exposure#35]
I use the provided `eval()` function in `net.py` to evaluate some JPG images with sizes around 500x500.
The evaluation time of an image I calculated is on average about 3.5s-4s on my GPU. And each retouch process costs 700ms to 800ms. 

However you say `An unoptimized version takes 30ms for inference on an NVIDIA TITAN X (Maxwell) GPU. `
I understand that you evaluate and get a retouched photo only takes 30ms? Is my understanding correct?
How can I speed up if you test it in 30ms?

**Comment by yuanming-hu** [comment]
The 30ms performance number is based on batched inference on low-res images (32 or 64 images of resolution 64x64). Retouching a high-res photo takes longer time in our current code since the pipeline is unoptimized. An optimized implementation should be able to achieve real-time performance, though we didn't implement it.

**Comment by vikiQiu** [comment]
Ok, thank you. Hope for your optimized implementation.
